# Generated by Django 4.2.10 on 2024-12-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_audiorecording_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
